version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: dockerfiles/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/vite-project
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/postgreSQL:/docker-entrypoint-initdb.d
volumes:
  postgres-data: